name: 🛠️ Implementation
description: This is an implementation ticket intended for use by the maintainers of dbt-extractor
title: "[<project>] <title>"
labels: ["user docs"]
body:
  - type: markdown
    attributes:
      value: This is an implementation ticket intended for use by the maintainers of dbt-extractor
  - type: checkboxes
    attributes:
      label: Housekeeping
      description: >
        A couple friendly reminders:
          1. Link any blocking issues in the "Blocked on" field under the "Core devs & maintainers" project.
      options:
        - label: I am a maintainer of dbt-extractor
          required: true
  - type: textarea
    attributes:
      label: Short description
      description: |
        Describe the scope of the ticket, a high-level implementation approach and any tradeoffs to consider
    validations:
      required: true
  - type: textarea
    attributes:
      label: Acceptance criteria
      description: |
        What is the definition of done for this ticket? Include any relevant edge cases and/or test cases
    validations:
      required: true
  - type: textarea
    attributes:
      label: Context
      description: |
        Provide the "why", motivation, and alternative approaches considered -- linking to previous refinement issues, spikes, docs as appropriate
          validations:
    validations:
      required: false
